version: 2
updates:
  # Keep npm dependencies up to date
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    groups:
      # Group TypeScript-related updates
      typescript:
        patterns:
          - "typescript"
          - "@types/*"
          - "tsx"
      # Group build tools
      build-tools:
        patterns:
          - "postject"
    commit-message:
      prefix: "chore(deps)"

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    commit-message:
      prefix: "chore(ci)"
