name: CI (Windows)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.20.0 --activate
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build TypeScript
        run: pnpm run build
      - name: Build SEA executable
        run: bash scripts/build-sea.sh
      - name: Verify executable
        shell: pwsh
        run: |
          if (-not (Test-Path 'build\maven-cli.exe')) {
            Write-Error 'Executable not found'
            exit 1
          }
          $output = & 'build\maven-cli.exe' 2>&1
          if ($output -notmatch 'Maven CLI bootstrap ready') {
            Write-Error "Expected output not found: $output"
            exit 1
          }
          Write-Host "✓ Smoke test passed"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: maven-cli-windows
          path: build/maven-cli.exe

