name: Release (Windows)

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup pnpm
        run: corepack enable && corepack prepare pnpm@10.20.0 --activate
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install deps
        run: pnpm install --frozen-lockfile
      - name: Build TypeScript
        run: pnpm run build
      - name: Build SEA executable
        run: bash scripts/build-sea.sh
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          gh release create "$env:TAG_NAME" build/maven-cli.exe --title "$env:TAG_NAME" --notes "Windows CLI executable" --draft

