name: Release (Multi-Platform SEA)

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.20.0 --activate
      - name: Install deps
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run SEA build script
        run: bash scripts/build-sea.sh
      - name: Upload artifact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Uploading build/maven-cli.exe to release $env:TAG_NAME"
          gh release upload "$env:TAG_NAME" build/maven-cli.exe --clobber

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.20.0 --activate
      - name: Install deps
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run SEA build script
        run: bash scripts/build-sea.sh
      - name: Rename binary for release
        run: mv build/maven-cli build/maven-cli-linux
      - name: Upload artifact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Uploading build/maven-cli-linux to release $TAG_NAME"
          gh release upload "$TAG_NAME" build/maven-cli-linux --clobber

  release-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@10.20.0 --activate
      - name: Install deps
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run SEA build script
        run: bash scripts/build-sea.sh
      - name: Rename binary for release
        run: mv build/maven-cli build/maven-cli-macos
      - name: Upload artifact to release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Uploading build/maven-cli-macos to release $TAG_NAME"
          gh release upload "$TAG_NAME" build/maven-cli-macos --clobber

  create-release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Create draft release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Creating draft release $TAG_NAME"
          gh release create "$TAG_NAME" --title "$TAG_NAME" --notes "Multi-platform release" --draft --repo "${{ github.repository }}"
