name: Release (Windows SEA)

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 25
        uses: actions/setup-node@v4
        with:
          node-version: '25.x'
          check-latest: true
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run SEA build script
        run: bash scripts/build-sea.sh
      - name: Create GitHub Release (draft)
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          release_name: ${{ github.ref_name }}
          draft: true
          prerelease: false
          body: "Automated draft release from CI"
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload release asset (EXE)
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build/maven-cli.exe
          asset_name: maven-cli.exe
          asset_content_type: application/octet-stream
