name: Release (Windows SEA)

on:
  push:
    tags: ['v*']

permissions:
  contents: write

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node 25
        uses: actions/setup-node@v4
        with:
          node-version: '25.x'
          check-latest: true
      - name: Install pnpm
        run: corepack enable && corepack prepare pnpm@latest --activate
      - name: Install deps
        run: pnpm install
      - name: Build project
        run: pnpm run build
      - name: Run SEA build script
        run: bash scripts/build-sea.sh
      - name: Create draft release and upload EXE using gh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAG_NAME: ${{ github.ref_name }}
        run: |
          echo "Creating draft release $TAG_NAME and uploading build/maven-cli.exe"
          gh release create "$TAG_NAME" build/maven-cli.exe --title "$TAG_NAME" --notes "Automated draft release from CI" --draft --repo "${{ github.repository }}"
